### ISSUE TITLE
can't install with laravel 5.6.29 (currently the latest version)

### ISSUE THREAD

**Issue by chilly2go** [pdffiller/laravel-influx-provider#12]
output from composer:

> Problem 1
>    -Conclusion: remove laravel/framework v5.6.29
>    -Conclusion: don't install laravel/framework v5.6.29
>    -pdffiller/laravel-influx-provider v1.6.0 requires illuminate/log 5.2.*|5.3                                                                    >.*|5.4.* -> satisfiable by illuminate/log[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.2. [...]

also: your readme states changes to config/app.php. AFAIK you do not have to do this anymore thanks to autodiscovery

**Comment by sergeyklay** [comment]
@chilly2go Could you please send a PR?

**Comment by chilly2go** [comment]
I assume you mean a pull request for the suggested readme changes. (as I have not yet made a PR for another repo I will first look into how this all works together. AFAIK I have to fork it to commit the changes to the fork and after that I can do the PR. If that is wrong it might all take a little longer....)

I can't change the package requirements as I have not written the code myself and can't tell if it would break something.
