### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by naex** [pdffiller/laravel-influx-provider#16]
Hi, is it possible to add Laravel 5.8 support? Thanks

**Comment by sergeyklay** [comment]
Pull requests are always welcome :)

**Comment by naex** [comment]
OK. Request sent.

**Comment by sergeyklay** [comment]
Just release a new version https://github.com/pdffiller/laravel-influx-provider/releases/tag/v1.6.4
Thank you for contributing
