### ISSUE TITLE
Laravel 5.3 & composer

### ISSUE THREAD

**Issue by strebl** [pdffiller/laravel-influx-provider#2]
Hi

I have two questions:
- Do you plan Laravel 5.3 support?
- I can't find the package on composer, did you publish it?

**Comment by abelkbil** [comment]
![image](https://cloud.githubusercontent.com/assets/1478274/18863915/60c76022-84b1-11e6-8320-edfcfa8b37de.png)
I can't find the package on composer,

**Comment by sergeyklay** [comment]
Hello @strebl @abelkbil

We'll try to sort out with Packagist ASAP.
The Laravel 5.3 support wil be introduced in next release.

Thank you for contributing!

**Comment by sergeyklay** [comment]
https://packagist.org/packages/pdffiller/laravel-influx-provider

**Comment by sergeyklay** [comment]
Fixed in the `master` branch. We'll release the new version soon

**Comment by sergeyklay** [comment]
Released:
https://github.com/pdffiller/laravel-influx-provider/releases/tag/1.3
