### ISSUE TITLE
About laravel 5.4 

### ISSUE THREAD

**Issue by admover** [pdffiller/laravel-influx-provider#6]
Hi.
  When can support 5.4
thk.

**Comment by sergeyklay** [comment]
Cc: @apictapx

**Comment by apictapx** [comment]
I don't contribute to this repo no more. Sorry.

**Comment by admover** [comment]
Thanks for the reply.
And what can i do now? wait or give up?

**Comment by pvgennip** [comment]
@admover Wait for https://github.com/pdffiller/laravel-influx-provider/pull/8 to be merged :-)

**Comment by sergeyklay** [comment]
Implemented in the [1.5.0 version](https://github.com/pdffiller/laravel-influx-provider/releases/tag/v1.5.0). Thank you for contributing!

**Comment by admover** [comment]
Thank you all.
